'''module to import and read follow up update generated by excell
    into list alaa zak  23-092018'''

import csv
import sys
from datetime import datetime

from maneger.models import Project, Client, ProjectClass, Comment, Finance, Achievement, Plan, Contractor, Legacyids
from django.utils import timezone

# 0 mosalsal
# 1 project_code
# 2 eetimad_no
# 3 client
# 4 project_name
# 5 total_budget
# 6 e_2013
# 7 e_2015
# 8 e_2016
# 9 e_2017
# 10 e_2018
# 11 e_2019
# 12 e_2020
# 13 e_2021
# 14 comment
# 15 contractor

keys = dict(
mosalsal = 0,
project_code = 1,
eetimad_no = 2,
client = 3,
project_name = 4,
total_budget = 5,
e_2013 = 6,
e_2015 = 7,
e_2016 = 8,
e_2017 = 9,
e_2018 = 10,
e_2019 = 11,
e_2020 = 12,
e_2021 = 13,
comment = 14,
contractor = 15
)


file = 'planp.csv'
skippers = ['اجمالى','الاجمالي','']

projects_list = []
def hatp():
    with open(file, newline='') as csvfile:
        reader = csv.reader(csvfile)
        for row in reader:
        
            if row[0] in skippers:
                continue
        
           ##
            print(row[keys['e_2013']].strip(),'---000----')
            one_project = dict(
                ettimad_no=int(row[keys['eetimad_no']].strip()),
                e_2013=0 if row[keys['e_2013']].strip()=='' else e_2013=int(row[keys['e_2013']].strip()),
                e_2015=0 if row[keys['e_2015']].strip()=='' else e_2015=int(row[keys['e_2015']].strip()),
                e_2016=0 if row[keys['e_2016']].strip()=='' else e_2016=int(row[keys['e_2016']].strip()),
                e_2017=0 if row[keys['e_2017']].strip()=='' else e_2017=int(row[keys['e_2017']].strip()),
                e_2018=0 if row[keys['e_2018']].strip()=='' else e_2018=int(row[keys['e_2018']].strip()),
                e_2019=0 if row[keys['e_2019']].strip()=='' else e_2019=int(row[keys['e_2019']].strip()),
                e_2020=0 if row[keys['e_2020']].strip()=='' else e_2020=int(row[keys['e_2020']].strip()),
                0 if '' else e_2021=int(row[keys['e_2021']].strip()),
                comment=row[keys['e_2021']].strip()
                )

            projects_list.append(one_project)

    

    for project in projects_list:
    
        
        p = Project.objects.get(legacyids=project['ettimad_no'])
        plans = {
            2013:project['e_2013'],
            2015:project['e_2015'],
            2016:project['e_2016'],
            2017:project['e_2017'],
            2018:project['e_2018'],
            2019:project['e_2019'],
            2020:project['e_2020'],
            2021:project['e_2021'],
            }
        for plan,cash in plans.items():
            
       
       
      
    
     
        
        
            if (project['plan_year'].strip()) != '':
                plantext = project['plan_year'].strip()
            plan_yers_array = plantext.split('/')
            print(plan_yers_array,project['name'])
        # replace 0 with one 2018-1015
            plan_year = int(plan_yers_array[1].strip())
            cash = float(project['current_year_budget'].strip()) 
            pl = Plan.objects.create(project=p, cash=cash, year=plan_year)

        #tentaitive past and future plans
        # keys: total_budjet  past_years_budjet
        past_years_budjet = int(project['past_years_budjet'].strip())
        total_budjet = int(project['total_budjet'].strip())
        #current_year_budget
        current_year_budget = int(project['current_year_budget'].strip())
        if past_years_budjet > 0:
            prev_pl = Plan.objects.create(project=p, cash=past_years_budjet, year=plan_year-1)
        future_budget = total_budjet - past_years_budjet - current_year_budget

        if future_budget > 0:
            future_pl = Plan.objects.create(project=p, cash=future_budget, year=plan_year+1)

        #handeling past spent
        # key: past_total_spent
        past_total_spent = float(project['past_total_spent'].strip())
        if past_total_spent > 0:
            pf = Finance.objects.create(project=p, title='past spent', cash=past_total_spent,pub_date='2017-5-1', comment='-----')

        #handeling current year spent
        # key: current_year_spent
        current_year_spent =  float(project['current_year_spent'].strip())
        ###    
        #if current_year_spent > 0:
        cf = Finance.objects.create(project=p, title='current year spent', cash=current_year_spent,pub_date='2017-9-1', comment='-----')

         #handeling achievment
        # key: achivement_progress
        achivement_progress =  float(project['achivement_progress'].strip())
        ###
        #if current_year_spent > 0:
        achi = Achievement.objects.create(project=p, title='Achievement tilldate', percent=achivement_progress, pub_date=datetime(2018,9,1), comment='-----')
        
         #handeling status
        # key: status
        status = project['status']
        sta = Comment.objects.create(project=p, text=status, pub_date=str(plan_year)+'-9-1')
    
        #et = 


        




        
    """
     p = Project.create(
            name=project[name],
            client=
    """
