# Generated by Django 2.1 on 2018-09-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maneger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='project',
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ManyToManyField(to='maneger.Project'),
        ),
    ]
