# Generated by Django 2.1 on 2018-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maneger', '0002_auto_20180913_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='plan',
            field=models.ManyToManyField(to='maneger.Plan'),
        ),
    ]
