# Generated by Django 2.1 on 2018-09-15 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maneger', '0003_auto_20180913_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maneger.Project'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('project', 'year')},
        ),
    ]
