# Generated by Django 2.1 on 2018-09-15 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maneger', '0005_auto_20180915_1032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together=set(),
        ),
    ]
