# Generated by Django 2.1 on 2018-09-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maneger', '0006_auto_20180915_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('project', 'year')},
        ),
    ]
