# Generated by Django 2.1 on 2018-09-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maneger', '0008_auto_20180923_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractors',
        ),
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ManyToManyField(null=True, to='maneger.Contractor'),
        ),
    ]
