# Generated by Django 2.1 on 2018-11-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maneger', '0009_auto_20180926_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legacyids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.IntegerField(null=True)),
                ('eetimad_no', models.IntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maneger.Project')),
            ],
        ),
    ]
